# Generated by Django 3.1.3 on 2020-11-26 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialquantity',
            options={'verbose_name_plural': 'Material Quantities'},
        ),
    ]
