# Generated by Django 3.1.3 on 2020-11-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20201126_0341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialstock',
            options={'verbose_name_plural': 'Material Stocks'},
        ),
        migrations.AddConstraint(
            model_name='materialquantity',
            constraint=models.CheckConstraint(check=models.Q(quantity__gt=0), name='quantity__gt_0'),
        ),
    ]
