# Generated by Django 3.1.3 on 2020-11-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20201126_0355'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='materialquantity',
            constraint=models.UniqueConstraint(fields=('product', 'ingredient'), name='unique_product_ingredient'),
        ),
    ]
